from enum import Enum

class PassageResult(Enum):
    CAR_NOT_FOUND = "CAR_NOT_FOUND"
    ARRIVAL = "ARRIVAL"
    DEPARTURE_WITH_MONEY_WITHDRAW = "DEPARTURE_WITH_MONEY_WITHDRAW"
    ALREADY_PROCESSED_IN_SESSION = "ALREADY_PROCESSED_IN_SESSION"
    DEPARTURE_USER_NO_MONEY = "DEPARTURE_USER_NO_MONEY" 